# Generated by Django 4.2.21 on 2025-05-23 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('cover', models.URLField(max_length=500)),
                ('publisher', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('author_info', models.TextField()),
                ('author_photo', models.URLField(max_length=500)),
                ('customer_review_rank', models.IntegerField()),
                ('subTitle', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.category')),
            ],
        ),
    ]
