# Generated by Django 4.2.21 on 2025-05-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bio_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, help_text='임베딩 벡터 최종 업데이트 시간', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='embedding_vector',
            field=models.TextField(blank=True, help_text='사용자 메타데이터 기반 임베딩 벡터', null=True),
        ),
    ]
