# Generated by Django 4.2.21 on 2025-05-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_thread_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_at']},
        ),
    ]
