<template>
  <div class="background-image">
    <!-- 배경 이미지 -->
    <div class="overlay"></div> <!-- 반투명 회색 필터 오버레이 -->
    <h1 class="focus-in-expand main-title">
        Welcome to Our Site
    </h1>
  </div>
</template>

<script setup>
// 심플한 배경 이미지 컴포넌트
</script>

<style scoped>
.main-title {
  position: absolute;
  top: 50%;
  right: 50%;
  transform: translate(-50%, -50%);
  color: white;
  font-size: 3rem;
  text-align: center;
  z-index: 3; /* 텍스트가 오버레이 위에 표시되도록 */
  font-family: 'Arial', sans-serif; /* 원하는 폰트로 변경 가능 */
}

.background-image {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-image: url('/MainImage.jpg');
  background-size: cover;
  background-position: center;
  z-index: 1;
}

/* 반투명 회색 필터 오버레이 */
.overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.4); /* 검은색 반투명 필터 (40% 투명도) */
  z-index: 2;
}

@media (max-width: 1024px) {
  .background-image {
    width: 100%;
  }
}

@media (max-width: 768px) {
  .background-image {
    width: 100%;
    height: 100%;
  }
}
.focus-in-expand {
	-webkit-animation: focus-in-expand 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: focus-in-expand 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2025-5-27 11:1:25
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation focus-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes focus-in-expand {
  0% {
    letter-spacing: -0.5em;
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes focus-in-expand {
  0% {
    letter-spacing: -0.5em;
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}


</style>
